### ISSUE TITLE
Doesn't work if not using TestCase subclasses

### ISSUE THREAD

**Issue by cartertinney** [rudineirk/pytest-mocha#2]
This library seems to be based on a requirement that organizational classes of tests inherit from unittest.TestClass, however test classes in pytest generally inherit from "object" in order to correctly handle fixtures and their parameterization. When using "object" inheritance with pytest-mocha however, all tests are simply called "()" (the color of the text still correctly indicates success/failure)

Could this library be fixed to be compatible with the patterns typical to pytest?

Test Code:
```python
import pytest

def foo(arg):
    return 'bar'

@pytest.fixture(params=["thing", "thang"])
def thing(request):
    return request.param

class TestClassForFoo(object):

    def test_foo(self, thing):
        '''subsection :: test description'''
        assert foo(thing) == 'bar'
```

Output:
```
collected 2 items

TestClassForFoo :: test_thing.py
    ✓ ()
    ✓ ()                                                        [100%]
========================== 2 passed in 0.07 seconds ===========================
```

**Comment by rudineirk** [comment]
After some digging I found that this problem just happens on pytest<2.x. On pytest 4.3.0 it works with and without `TestClass` as base.

Either way, I fixed the behaviour on pytest 2.x, should be fixed on the latest release.
